import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0d631b",
        "on-primary": "#ffffff",
        "primary-container": "#2e7d32",
        "on-primary-container": "#adf7b9",
        "primary-fixed": "#98f2a4",
        "primary-fixed-dim": "#79d886",
        "on-primary-fixed": "#05200c",
        "on-primary-fixed-variant": "#145320",

        secondary: "#005db7",
        "on-secondary": "#ffffff",
        "secondary-container": "#64a1ff",
        "on-secondary-container": "#001c41",
        "secondary-fixed": "#b6caff",
        "secondary-fixed-dim": "#6fa9ff",
        "on-secondary-fixed": "#061633",
        "on-secondary-fixed-variant": "#004482",

        tertiary: "#00631e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#277d34",
        "on-tertiary-container": "#339941",
        "tertiary-fixed": "#9df6a2",
        "tertiary-fixed-dim": "#7edd84",
        "on-tertiary-fixed": "#012105",
        "on-tertiary-fixed-variant": "#044b18",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",

        background: "#fcf9f8",
        "on-background": "#191c19",
        surface: "#fcf9f8",
        "on-surface": "#191c19",
        "surface-dim": "#dcd9d8",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f1eeed",
        "surface-container-high": "#ebe8e7",
        "surface-container-highest": "#e6e1dd",
        "on-surface-variant": "#424940",
        outline: "#72796f",
        "outline-variant": "#c2c9bc",
        "inverse-surface": "#2e312d",
        "inverse-on-surface": "#f0f1ec",
        "inverse-primary": "#79d886",

        bosque: "#0D3B0D",
        "verde-semta": "#0D631B",
      },
      fontFamily: {
        "display-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-xl": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-md": ['"Plus Jakarta Sans"', "sans-serif"],
        "headline-sm": ['"Plus Jakarta Sans"', "sans-serif"],
        "body-lg": ['"Inter"', "sans-serif"],
        "body-md": ['"Inter"', "sans-serif"],
        "body-sm": ['"Inter"', "sans-serif"],
        "label-lg": ['"Inter"', "sans-serif"],
        "label-md": ['"Inter"', "sans-serif"],
        "label-caps": ['"Inter"', "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "display-lg-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600", letterSpacing: "0.01em" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.02em" }],
        "label-caps": ["11px", { lineHeight: "16px", fontWeight: "700", letterSpacing: "0.08em" }],
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "gutter-desktop": "2rem",
        "gutter-mobile": "1rem",
      },
      maxWidth: {
        "container-semta": "1240px",
      },
      boxShadow: {
        "card-semta": "0 1px 2px rgba(25,28,25,0.06), 0 8px 24px rgba(25,28,25,0.08)",
        "soft-semta": "0 8px 30px rgba(44,62,46,0.10)",
      },
    },
  },
  plugins: [],
};
export default config;