import type { LucideProps } from "lucide-react";
import {
  Armchair,
  ArrowDown,
  ArrowUp,
  Award,
  BadgeCheck,
  BarChart3,
  BellRing,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cog,
  Dog,
  DoorOpen,
  Download,
  Droplets,
  Eye,
  ExternalLink,
  FileText,
  Flag,
  FlaskConical,
  Flower2,
  FolderOpen,
  Frown,
  Gift,
  GraduationCap,
  Hammer,
  Handshake,
  HelpCircle,
  History,
  Home,
  Hourglass,
  Images,
  Landmark,
  Layers,
  Leaf,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  MessagesSquare,
  Moon,
  Mountain,
  Package,
  Phone,
  PieChart,
  PlayCircle,
  QrCode,
  Recycle,
  Rocket,
  Route,
  School,
  ScrollText,
  Search,
  SearchX,
  Send,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  SolarPanel,
  Sprout,
  Star,
  Store,
  Sun,
  Table,
  ThumbsUp,
  Tractor,
  TrendingUp,
  Truck,
  Users,
  Video,
  Wrench,
  X,
} from "lucide-react";

import { cn } from "@/lib/utils";

const materialToLucide: Record<string, React.ComponentType<LucideProps>> = {
  account_balance: Landmark,
  agriculture: Tractor,
  analytics: BarChart3,
  arrow_forward: ChevronRight,
  article: FileText,
  arrow_upward: ArrowUp,
  assignment_turned_in: CheckCircle2,
  badge: BadgeCheck,
  bar_chart: BarChart3,
  biotech: FlaskConical,
  book: Book,
  business: Briefcase,
  calendar_month: Calendar,
  calendar_today: CalendarDays,
  call: Phone,
  campaign: Megaphone,
  chat: MessageSquare,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  close: X,
  data_table: Table,
  description: ScrollText,
  diversity_1: Users,
  diversity_3: Users,
  donut_large: PieChart,
  door_front: DoorOpen,
  download: Download,
  eco: Leaf,
  engineering: Wrench,
  event: Calendar,
  event_note: Calendar,
  event_seat: Armchair,
  event_available: Calendar,
  event_upcoming: CalendarPlus,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  favorite: Gift,
  flag: Flag,
  folder_open: FolderOpen,
  forum: MessagesSquare,
  gpp_bad: ShieldX,
  group: Users,
  groups: Users,
  handshake: Handshake,
  handyman: Hammer,
  help_outline: HelpCircle,
  history: History,
  history_edu: History,
  home: Home,
  hourglass_top: Hourglass,
  info: HelpCircle,
  inventory_2: Package,
  keyboard_arrow_down: ArrowDown,
  layers: Layers,
  light_mode: Sun,
  dark_mode: Moon,
  link: ExternalLink,
  local_florist: Flower2,
  local_shipping: Truck,
  location_on: MapPin,
  location_city: MapPin,
  lock: Lock,
  mail: Mail,
  map: MapPin,
  menu: Menu,
  menu_book: BookOpen,
  model_training: GraduationCap,
  monitoring: BarChart3,
  notifications_active: BellRing,
  open_in_new: ExternalLink,
  park: Leaf,
  pets: Dog,
  photo_camera: Camera,
  photo_library: Images,
  pin_drop: MapPin,
  place: MapPin,
  play_circle: PlayCircle,
  potted_plant: Sprout,
  privacy_tip: ShieldAlert,
  psychology: Brain,
  public: Home,
  qr_code_scanner: QrCode,
  quiz: HelpCircle,
  recycling: Recycle,
  redeem: Gift,
  rocket_launch: Rocket,
  route: Route,
  schedule: Clock,
  school: School,
  search: Search,
  search_off: SearchX,
  send: Send,
  sentiment_dissatisfied: Frown,
  settings: Cog,
  shield: Shield,
  solar_power: SolarPanel,
  spa: Leaf,
  star: Star,
  storefront: Store,
  tag: Award,
  terrain: Mountain,
  thumb_up: ThumbsUp,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  videocam: Video,
  visibility: Eye,
  water: Droplets,
  water_ph: Droplets,
  workspace_premium: Award,
};

export function MaterialIcon({ name, className }: { name: string; className?: string }) {
  const Icon = materialToLucide[name] ?? Circle;
  return (
    <span aria-hidden="true" className={cn("inline-flex shrink-0 items-center", className)}>
      <Icon width="1em" height="1em" strokeWidth={2} aria-hidden="true" />
    </span>
  );
}
